# Generated by Django 4.2.20 on 2025-04-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="article",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
