# Generated by Django 4.2.20 on 2025-05-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0002_alter_item_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="link",
            field=models.CharField(blank=True, null=True),
        ),
    ]
